### ISSUE TITLE
Fix /chase colour issue

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#34]
This issue has existed for quite some time. When a /chase is active, everyone gets their colour set to white, except for the player being chased (who gets red). 

However, sometimes other players are able to get other colours. I'm not sure in exactly which circumstances this is the case, I believe mainly when new players join the server.

Screenshot: http://i.imgur.com/2bw4gCX.png

ID 38 was being chased, however ID 24 and 25 had colours that were not white.

Is there anything that can be done about this? It ruins the point of the minigame in a way as the player in question is harder to locate.

**Comment by ghost** [comment]
Fixed by https://github.com/LVPlayground/playground/commit/2b0232da2de4a0cfa9221e0b88c3a951e2b07457

FWIW: I have tested /chase on the prod. server since this patch was implemented and everything works as expected. The only player to have a coloured marker on the mini-map/radar is the player being chased.

**Comment by xhoogland** [comment]
Good to hear, Granny!

Unfortunately this problem isn't fully fixed since the following sequence still ends up with players NOT being red or white:
1. Start a minigame succesfully (so with enough sign-ups)
2. Start a chase
3. Succeed with/End the minigame.
4. Detect players without the red or white color.

(Was also described in the commit.) Feel free to close this issue again, but then please open a new issue describing the problem with minigames.

**Comment by jadegraaf** [comment]
@Xanland Can I summarize your message to: players coming back from a minigame are not given the white color?

**Comment by xhoogland** [comment]
Yes.
