### ISSUE TITLE
Reset teleport rights for free VIP users

### ISSUE THREAD

**Issue by ghost** [LVPlayground/playground#78]
Hi , at X-mas Month we give player Give Temp Vip Rights so when they have set /my teleport off
and  now When we remove That Script Their Teleport is OFF Only we can't Tp them i have Try on 2-4 player their Teleport is Off

**Comment by debuggest3** [comment]
Over Christmas, registered players were given free VIP access. Many of them disabled their teleport with /my teleport off. That free VIP period has expired, and those players who disabled their teleport still have it disabled.

Those free VIP players should have their teleport turned back on.

**Comment by HopperLVP** [comment]
Dgrp who are u again ?

**Comment by debuggest3** [comment]
Done.

**Comment by ghost** [comment]
Tested on a couple players (who've logged in / out several times) since you performed the change, dgrp -- the issue still exists. Is it possible that the server will require a restart before this takes effect?

**Comment by HopperLVP** [comment]
to fix it We need Russle Or Xanland

**Comment by debuggest3** [comment]
Can you provide me with names of players who are still affected on IRC?

**Comment by debuggest3** [comment]
Apparently, there is still a way to turn the teleportation setting off without having VIP rights. I hope this is fixed as per https://github.com/LVPlayground/playground/pull/82, but in the meantime these queries can be used to find these players and correct the setting:

```
SELECT u.user_id, u.username, m.settings FROM users_mutable m LEFT JOIN users u ON u.user_id = m.user_id WHERE ((m.`settings` >> 1) & 1) = 1 AND u.is_vip = 0
```

```
UPDATE users_mutable m LEFT JOIN users u ON u.user_id = m.user_id SET m.settings = m.settings ^ 2 WHERE ((m.`settings` >> 1) & 1) = 1 AND u.is_vip = 0
```

I have reset the setting for 4 players again.
